sudo: false
language: minimal
services: docker

env:
  global:

before_install:
  - docker pull gcr.io/cloud-builders/gcloud:latest
  - docker pull unspecifiedllc/gcloud-config:latest

install:
  - docker volume create activated_service-account
  - docker run -it --rm
    --mount source=activated_service-account,target=/root/.config/gcloud
    -e GCLOUD_SERVICE_KEY=${GCLOUD_SERVICE_KEY}
    unspecifiedllc/gcloud-config:latest

script:
  - docker run -it --rm
    --mount source=activated_service-account,target=/root/.config/gcloud
    gcr.io/cloud-builders/gcloud:latest auth list

after_script:
  - docker volume rm activated_service-account